### ISSUE TITLE
When the dark theme loads, the background is white so you just see the 'x' in the logo

### ISSUE THREAD

**Issue by plainspace** [oxidecomputer/design-site#22]
To fix, the background of the dark theme should be dark and the light should be light so that the respective logo is fully visible as the rest of the elements animate in

**Comment by fivenp** [comment]
Any chance you could create a video to be able to reproduce it? I tried with disabling the cache but even then it's not really visible to me....

**Comment by plainspace** [comment]
Closing. Not an issue any longer.
