### ISSUE TITLE
Blog post summaries have truncated urls

### ISSUE THREAD

**Issue by deric4** [oxidecomputer/design-site#31]
I know this isn't technically the correct project but didn't quickly see anywhere else to report this kinda thing. The URLs in the blog post summaries look like they're getting truncated if they're at the very end. 

https://oxide.computer/blog/

![Screen Shot 2020-01-09 at 10 17 54 AM](https://user-images.githubusercontent.com/5762138/72085023-2f813180-32ca-11ea-9e70-00b8fec551e0.png)

Really enjoy the podcasts btw!

**Comment by plainspace** [comment]
Thanks for reporting this! Missed it in this repo. We launched a new site and this isn't an issue any longer.
